buildscript {
    repositories {}
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.+'
        classpath group: 'wtf.gofancy.fancygradle', name: 'wtf.gofancy.fancygradle.gradle.plugin', version: '1.1.+'
    }
}

plugins {
    id 'java'
    id 'idea'
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'wtf.gofancy.fancygradle'

version = project.mod_version
group = project.maven_group
archivesBaseName = project.archives_base_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'stable', version: '39-1.12'
    accessTransformer = file('src/main/resources/META-INF/hdsutils_at.cfg')
    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            jvmArg '-Dmixin.hotSwap=true'
			jvmArg '-Dmixin.checks.interfaces=true'
			jvmArg '-Dmixin.debug=true'

            environment 'MC_VERSION', '1.12.2'

            mods {
                hdsutils {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            jvmArg '-Dmixin.hotSwap=true'
			jvmArg '-Dmixin.checks.interfaces=true'

            environment 'MC_VERSION', '1.12.2'

            mods {
                hdsutils {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        ext.refMap = 'mixins.' + archives_base_name + '.refmap.json'

        java {
            srcDirs = ["src/main/java"]
        }

        resources {
            srcDirs = ["src/main/java", "src/main/resources"]
        }
    }

    test {
        java {
            srcDirs = ["src/test/java"]
        }
        resources {
            srcDirs = ["src/test/resources"]
        }
    }

    main.output.setResourcesDir(main.java.outputDir)
}

repositories {
    mavenCentral()
    maven {
        name = 'thiakil'
        url = 'https://maven.thiakil.com'
    }
    maven {
        name = 'blamejared'
        url = 'https://maven.blamejared.com'
    }
    maven {
        name = 'cofh'
        url = 'https://maven.covers1624.net'
    }
    maven {
        name = 'jei'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        name = 'tterrag'
        url = 'https://maven.tterrag.com/'
    }
    maven {
        name = 'youyihj'
        url = 'https://friendlyhj.github.io/maven'
    }
    maven {
        name = 'hellfirepvp'
        url = 'https://maven.hellfiredev.net/'
    }
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/maven'
    }
    maven {
        name = "CurseMaven"
        url = 'https://cfa2.cursemaven.com'
    }
    maven {
        name = 'CleanroomMC'
        url = 'https://maven.cleanroommc.com'
    }
}

configurations {
    embedded

    compileOnly.extendsFrom provided
    implementation.extendsFrom embedded
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    // Mixin related
    embedded fg.deobf('zone.rong:mixinbooter:7.0')
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    // Tweaked mods
    embedded fg.deobf('vazkii.botania:Botania:r1.10-363.148')
    embedded fg.deobf('com.azanor.baubles:Baubles:1.12-1.5.2')
    embedded fg.deobf("CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.682")
    embedded fg.deobf("CraftTweaker2:CraftTweaker2-API:4.1.9.6")
    embedded fg.deobf("CraftTweaker2:ZenScript:4.1.9.6")
    embedded fg.deobf('com.teamacronymcoders.base:base:1.12.2-3.13.0-SNAPSHOT.+')
    embedded fg.deobf('com.teamacronymcoders:ContentTweaker:1.12.2-4.9.1')
    embedded fg.deobf('cofh:RedstoneFlux:1.12-2.1.0.+:universal')
    embedded fg.deobf('mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.28-17')
    embedded fg.deobf('mezz.jei:jei_1.12.2:4.16.1.302')
    embedded fg.deobf('youyihj:zenutils:1.10.2')
    embedded fg.deobf('curse.maven:agricraft-225635:2609648')
    embedded fg.deobf('curse.maven:infinitylib-251396:2537265')
    embedded fg.deobf('curse.maven:thaumcraft-223628:2629023')
    embedded fg.deobf('curse.maven:factorytech-278822:3178832')
    // embedded fg.deobf('hellfirepvp.astralsorcery:astralsorcery:1.12.2-1.10.23-v161')
    embedded fg.deobf('curse.maven:bloodmagic-224791:2822288')
    embedded fg.deobf('curse.maven:guideapi-228832:2645992')
    embedded fg.deobf('curse.maven:thaumic-augmentation-319441:3536155')
    embedded fg.deobf('curse.maven:topography-297878:3065647')
    embedded fg.deobf('curse.maven:BNBGamingLib-229587:2698688')
    embedded fg.deobf('curse.maven:GregTechCEu-557242:4390983')

    /*embedded fg.deobf('curse.maven:FTBLibrary-237167:2985811') yes yes I'm working on it
    embedded fg.deobf('curse.maven:ItemFilters-309674:3003364')
    embedded fg.deobf('curse.maven:FTBQuests-289412:3156637')*/

}

fancyGradle {
    patches {
        resources
        coremods
        asm
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "hdsutils",
                "Specification-Vendor"    : "youyihj, GBLodb",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Specification-Vendor"    : "youyihj, GBLodb",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "ForceLoadAsMod"          : true,
                'TweakClass'              : 'org.spongepowered.asm.launch.MixinTweaker',
                "FMLAT"                   : "hdsutils_at.cfg"
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    duplicatesStrategy = 'include'

    inputs.property 'version', version
    inputs.property 'mcversion', '1.12.2'

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': version, 'mcversion': '1.12.2'
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
