buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'forge'
            url = 'https://files.minecraftforge.net/maven'
        }
        maven {
            name = 'sponge'
            url = 'https://repo.spongepowered.org/maven'
        }
    }
    dependencies {
        classpath('com.anatawa12.forge:ForgeGradle:2.3-1.0.+') { changing = true }
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

version = project.mod_version
group = project.maven_group
archivesBaseName = project.archives_base_name

sourceCompatibility = targetCompatibility = '1.8'

compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    version = project.forgeVersion
    runDir = 'run'
    mappings = project.mcpVersion
    def args = []
    args << '-Dmixin.hotSwap=true'
    args << '-Dmixin.checks.interfaces=true'
    args << '-Dmixin.debug.export=true'
    clientJvmArgs.addAll(args)
    serverJvmArgs.addAll(args)
}

repositories {
    mavenCentral()
    maven {
        name = 'thiakil'
        url = 'https://maven.thiakil.com'
    }
    maven {
        name = 'blamejared'
        url = 'https://maven.blamejared.com'
    }
    maven {
        name = 'cofh'
        url = 'https://maven.covers1624.net'
    }
    maven {
        name = 'jei'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        name = 'tterrag'
        url = 'https://maven.tterrag.com/'
    }
    maven {
        name = 'youyihj'
        url = 'https://friendlyhj.github.io/maven'
    }
    maven {
        name = 'hellfirepvp'
        url = 'https://maven.hellfiredev.net/'
    }
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/maven'
    }
    maven {
        name = "CurseMaven"
        url = 'https://cfa2.cursemaven.com'
    }
    maven {
        name = 'CleanroomMC'
        url = 'https://maven.cleanroommc.com'
    }
}

dependencies {

    // Mixin related
    compile 'zone.rong:mixinbooter:10.1'
    compile 'org.jooq:joor-java-8:0.9.14'
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    // Tweaked mods
    deobfCompile 'vazkii.botania:Botania:r1.10-363.148'
    deobfCompile 'com.azanor.baubles:Baubles:1.12-1.5.2'
    deobfCompile "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.685"
    deobfCompile 'com.teamacronymcoders.base:base:1.12.2-3.13.0-SNAPSHOT.+'
    deobfCompile 'com.teamacronymcoders:ContentTweaker:1.12.2-4.9.1'
    deobfCompile 'cofh:RedstoneFlux:1.12-2.1.0.+:universal'
    deobfCompile 'mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.28-17'
    deobfCompile 'mezz.jei:jei_1.12.2:4.16.1.302'
    deobfCompile 'youyihj:zenutils:1.10.2'
    deobfCompile 'curse.maven:agricraft-225635:2609648'
    deobfCompile 'curse.maven:infinitylib-251396:2537265'
    deobfCompile 'curse.maven:thaumcraft-223628:2629023'
    deobfCompile 'curse.maven:factorytech-278822:3178832'
    // deobfCompile 'hellfirepvp.astralsorcery:astralsorcery:1.12.2-1.10.23-v161'
    deobfCompile 'curse.maven:bloodmagic-224791:2822288'
    deobfCompile 'curse.maven:guideapi-228832:2645992'
    deobfCompile 'curse.maven:thaumic-augmentation-319441:3536155'
    deobfCompile 'curse.maven:topography-297878:3065647'
    deobfCompile 'curse.maven:BNBGamingLib-229587:2698688'
    deobfCompile 'curse.maven:GregTechCEu-557242:4390983'
    deobfCompile 'curse.maven:RailCraft-51195:3853491'
    deobfCompile 'curse.maven:Patchouli-306770:3162874'
    deobfCompile 'codechicken:CodeChickenLib:1.12.2-3.2.3.358:universal'
    deobfCompile 'curse.maven:LogisticsPipes-232838:4411480'
    deobfCompile 'curse.maven:BrandonsCore-231382:3408276'
    deobfCompile 'curse.maven:ProjectIntslligence-306028:2833640'
    deobfCompile 'team.chisel.ctm:CTM:MC1.12.2-1.0.2.31'
    deobfCompile 'team.chisel:Chisel:MC1.12.2-1.0.2.45'

    /*deobfCompile 'curse.maven:FTBLibrary-237167:2985811') yes yes I'm working on it
    deobfCompile 'curse.maven:ItemFilters-309674:3003364')
    deobfCompile 'curse.maven:FTBQuests-289412:3156637')*/

}

sourceSets {
    main {
        ext.refMap = 'mixins.' + archives_base_name + '.refmap.json'
    }
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version
    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }

    rename '(.+_at.cfg)', 'META-INF/$1' // Access Transformers
}

jar {
    manifest {
        attributes([
                "Specification-Title"         : archives_base_name,
                "Specification-Vendor"        : "youyihj, GBLodb",
                "Specification-Version"       : "1",
                "Implementation-Title"        : project.name,
                "Implementation-Version"      : project.mod_version,
                "Implementation-Timestamp"    : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "ForceLoadAsMod"              : true,
                "FMLAT"                       : "hdsutils_at.cfg",
                "FMLCorePlugin"               : "projecthds.herodotusutils.mixins.init.EarlyMixinInit",
                "FMLCorePluginContainsFMLMod" : true
        ])
    }
}
