# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: HerodotusUtilsBuilds

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run build.sh
      run: bash build.sh

    - name: Upload a Build Artifact.
      uses: actions/upload-artifact@v2.2.2
      with:
        name: hdsutils-build
        path: artifacts

  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Herodotus modpack repo
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/ProjectHDS/Herodotus

      - name: Move this mod to Herodotus modpack repo
        run: |
          rm -f /home/runner/work/HerodotusUtils/HerodotusUtils/artifacts/build file here
          rm -f /home/runner/work/Herodotus/Herodotus/.minecraft/mods/*
          mv -f /home/runner/work/HerodotusUtils/HerodotusUtils/artifacts/* /home/runner/work/Herodotus/Herodotus/.minecraft/mods/

      - name: Commit this mod to Herodotus modpack repo
        uses: EndBug/add-and-commit@v4
        with:
          author_name: friendlyhj
          author_email: youyi580@qq.com
          message: "Update Herodotus Utils Mod"
          add: "*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}